### ISSUE TITLE
About evaluation code

### ISSUE THREAD

**Issue by taokong** [ZhaoJ9014/Multi-Human-Parsing_MHP#1]
@ZhaoJ9014 
Hi, Jian. Very nice job of the multiple human parsing dataset. 
I'm here to ask if there is any official evaluation code or online servers for this task?

**Comment by ZhaoJ9014** [comment]
Dear Tao Kong,


Thank you very much for your interest in our Multi-Human Parsing (MHP) project.


For evaluation code, please refer to the "Evaluation" folder under our "Multi-Human-Parsing_MHP" repository. We have also set up a corresponding project websit, and the link is lv-mhp.github.io


We will release a more large-scale and comprehensive MHP v2.0 shortly, based on which we will organize the CVPR 2018 Workshop on Visual Understanding of Humans in Crowd Scene (VUHCS2018). This workshop is collaborated by NUS, CMU, and SYSU. You can find our CALL FOR PAPERS here (https://www.ece.nus.edu.sg/lv/files/VUHCS2018.pdf). Please feel free to drop us an email if you need other information.


Thank you and best regards.


Yours sincerely,


ZHAO Jian


---------------------------------------------
ZHAO Jian :: http://zhaoj9014.github.io<http://zhaoj9014.github.io/>
Ph.D. candidate, Learning and Vision Group
Department of Electrical and Computer Engineering
Faculty of Engineering
National University of Singapore
Vision and Machine Learning Lab, E4-#08-24, 4 Engineering Drive 3, National University of Singapore, Singapore 117583
Tel: (65) 9610 7176
Email: zhaojian90@u.nus.edu<mailto:zhaojian90@u.nus.edu>

________________________________
发件人: Tao Kong <notifications@github.com>
发送时间: 2018年3月23日 16:57
收件人: ZhaoJ9014/Multi-Human-Parsing_MHP
抄送: Zhao Jian; Mention
主题: [ZhaoJ9014/Multi-Human-Parsing_MHP] About evaluation code (#1)


@ZhaoJ9014<https://github.com/zhaoj9014>
Hi, Jian. Very nice job of the multiple human parsing dataset.
I'm here to ask if there is any official evaluation code or online servers for this task?

―

**Comment by taokong** [comment]
@ZhaoJ9014  Many thanks!
I think the task of multiple human parsing if very interesting and will follow the development.

**Comment by ZhaoJ9014** [comment]
Dear Tao Kong,


You're welcome. Please keep in touch.


Best regards.


Yours sincerely,


ZHAO Jian


---------------------------------------------
ZHAO Jian :: http://zhaoj9014.github.io<http://zhaoj9014.github.io/>
Ph.D. candidate, Learning and Vision Group
Department of Electrical and Computer Engineering
Faculty of Engineering
National University of Singapore
Vision and Machine Learning Lab, E4-#08-24, 4 Engineering Drive 3, National University of Singapore, Singapore 117583
Tel: (65) 9610 7176
Email: zhaojian90@u.nus.edu<mailto:zhaojian90@u.nus.edu>
________________________________
发件人: Tao Kong <notifications@github.com>
发送时间: 2018年3月24日 17:06
收件人: ZhaoJ9014/Multi-Human-Parsing_MHP
抄送: Zhao Jian; Mention
主题: Re: [ZhaoJ9014/Multi-Human-Parsing_MHP] About evaluation code (#1)


@ZhaoJ9014<https://github.com/ZhaoJ9014> Many thanks!
I think the task of multiple human parsing if very interesting and will follow the development.

―
