### ISSUE TITLE
MHP v2.0 dataset zip file from google drive is corrupt (error message when unzip)

### ISSUE THREAD

**Issue by ileniTudor** [ZhaoJ9014/Multi-Human-Parsing_MHP#10]
Cannot entirely unzip the zip file downloaded from google drive for the MHP v2.0 dataset. I have a message error: The archive is corrupted.

**Comment by ZhaoJ9014** [comment]
Hi, we have checked the data and link, and we didn't find any problem. Please re-check your downloading engine and re-download the whole dataset. Please feel free to drop us an email if you have further questions. Thx.

**Comment by archenroot** [comment]
@ileniTudor - the file is just fine, I downloaded all today and looks good.

**Comment by minsujang0** [comment]
I tried the zip file downloaded from Google Drive with two win10 laptops, and mine also says that the file is corrupted. Especially the files in val/ folder aren't working.

**Comment by ZhaoJ9014** [comment]
> I tried the zip file downloaded from Google Drive with two win10 laptops, and mine also says that the file is corrupted. Especially the files in val/ folder aren't working.

I have checked the link and it looks fine. Please check your network and retry your download. Please tell us if you have further problems:)

**Comment by minsujang0** [comment]
After trying, I found that only 7-zip can unzip the file successfully in Windows 10. I tried WinZip, Bandizip, Alzip, those programs couldn't interpret the header well.

**Comment by ZhaoJ9014** [comment]
> After trying, I found that only 7-zip can unzip the file successfully in Windows 10. I tried WinZip, Bandizip, Alzip, those programs couldn't interpret the header well.

Great.

**Comment by XuYunqiu** [comment]
When I use PIL to load the images, I get Warnings

UserWarning: Possibly corrupt EXIF data.  Expecting to read 131072 bytes but only got 0. Skipping tag 3

**Comment by JamesMcCullochDickens** [comment]
I solved the issue (just the downloading issue, not the corrupt image issue), by extracting the files individually to my drive, which is much slower, but ended up working eventually.
