### ISSUE TITLE
error on runing train_step1.py

### ISSUE THREAD

**Issue by zrl4836** [ZhaoJ9014/Multi-Human-Parsing_MHP#22]
Can you help me to analyse the error about it?

Reading data...
Traceback (most recent call last):
  File "train_step1.py", line 134, in <module>
    reader = data_provider('train.list')
  File "train_step1.py", line 92, in __init__
    seg = img_reader.pad(seg,np.uint8,False)
  File "/Multi-Human-Parsing/Nested_Adversarial_Networks/img_reader.py", line 42, in pad
    res[start_point:start_point+a] = img
ValueError: could not broadcast input array from shape (281,500,3) into shape (281,500)

**Comment by ridasalam** [comment]
Hi, what was the solution to this?

**Comment by vincentwei0919** [comment]
try to set flag to True on line 93 in train_step1.py  cause seg is a color image with three channels

**Comment by david-littlefield** [comment]
Solution [here](https://github.com/ZhaoJ9014/Multi-Human-Parsing/issues/37#issue-650342218)
