### ISSUE TITLE
Not able to download from Google Drive

### ISSUE THREAD

**Issue by KeremTurgutlu** [ZhaoJ9014/Multi-Human-Parsing_MHP#28]
First, thank you so much for open sourcing such a useful project like this. I was trying to download the dataset but i got the following error:

> "Sorry, you can't view or download this file at this time.
> 
> Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."

Then I tried Baidu, but everything was in Chinese so wasn't able to understand it. I wonder if there is another way to download the dataset without getting this error. Thanks a lot again!

**Comment by ZhaoJ9014** [comment]
> First, thank you so much for open sourcing such a useful project like this. I was trying to download the dataset but i got the following error:
> 
> > "Sorry, you can't view or download this file at this time.
> > Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."
> 
> Then I tried Baidu, but everything was in Chinese so wasn't able to understand it. I wonder if there is another way to download the dataset without getting this error. Thanks a lot again!

Hi, we have checked the google drive and baidu drive download links, and did not find any problem. Could you try again or use another VPN server?

**Comment by KeremTurgutlu** [comment]
It works now, thanks!
