### ISSUE TITLE
Is the baseline model/code published?

### ISSUE THREAD

**Issue by madhawav** [ZhaoJ9014/Multi-Human-Parsing_MHP#3]
The leaderboard page of the website mentions about base-line models for both tasks. Is the code/weights for these models published?

Thanks

**Comment by ZhaoJ9014** [comment]
Hi,

Thank you for your question.

Currently, we have released the dataset, the annotation tools, and source codes for NAN and evaluation metrics. The pre-trained models will be released in near future.

Thank you and best regards.

**Comment by JiangtianPan** [comment]
Hi, has the code for Instance-Agnostic Parsing part been released already in this github? I am interested in the code of FCN combined with ResNet101.

**Comment by ZhaoJ9014** [comment]
Hi,

Thank you for your question.

Yes. The code for the Instance-Agnostic Parsing part is included in our repository.

Thank you and best regards.

**Comment by ZhaoJ9014** [comment]
Hi,

Thank you for your question.

Yes. The code for the Instance-Agnostic Parsing part is included in our repository.

Thank you and best regards.


---------------------------------------------
ZHAO Jian :: http://zhaoj9014.github.io<http://zhaoj9014.github.io/>
Ph.D. candidate, Learning and Vision Group
Department of Electrical and Computer Engineering
Faculty of Engineering
National University of Singapore
Vision and Machine Learning Lab, E4-#08-24, 4 Engineering Drive 3, National University of Singapore, Singapore 117583
Tel: (65) 9610 7176
Email: zhaojian90@u.nus.edu<mailto:zhaojian90@u.nus.edu>

________________________________
发件人: Jiangtian Pan <notifications@github.com>
发送时间: 2018年7月17日 15:44
收件人: ZhaoJ9014/Multi-Human-Parsing_MHP
抄送: Zhao Jian; Comment
主题: Re: [ZhaoJ9014/Multi-Human-Parsing_MHP] Is the baseline model/code published? (#3)


Hi, has the code for Instance-Agnostic Parsing part been released already in this github? I am interested in the code of FCN combined with ResNet101.

―

**Comment by visonpon** [comment]
Hope the pretrained model would be released someday @ZhaoJ9014 , thanks~
