### ISSUE TITLE
Training your model with MHPv2

### ISSUE THREAD

**Issue by dmelladoc** [ZhaoJ9014/Multi-Human-Parsing_MHP#4]
Hello.

I'm trying to reproduce your model using the provided dataset, but I can't find on your code how to properly adapt the parsing annotations from MHPv2 and Nested Adversarial Networks, as shown on your paper. 
Specially due how each image has multiple parsing images in order to load them for training...
How do I use your dataset in your model?

Thanks beforehand

**Comment by ddddwee1** [comment]
In our implementation, the MHP is parsed to the same data formation as VOC2012. 

I think this process should be done yourself.

The code is only a replication of paper's original code, and it is only an overall structure of NAN network. While implementation, many pre-process and post-process should be developed by yourself depending on different datasets.
