### ISSUE TITLE
I can't find pose annotations in MHP_v2 dataset

### ISSUE THREAD

**Issue by zhirihuixin** [ZhaoJ9014/Multi-Human-Parsing_MHP#5]
I download the MHP_v2 dataset in baidu drive and I can't find pose annotations in MHP_v2 dataset. Please tell me where I can find it, thanks.

**Comment by ZhaoJ9014** [comment]
Hi,

Thank you for your question. 

Our MHP Dataset v2.0 has the annotations for both Multi-Human Parsing and Pose Estimation. Please refer to detailed information under "Download" of https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP

Thank you and best regards.
