### ISSUE TITLE
Code mistake and class_num value

### ISSUE THREAD

**Issue by b121351** [ZhaoJ9014/Multi-Human-Parsing_MHP#6]
There seems to be a small mistake(,) in the code while calling the function tf.nn.softmax at line 144

`/Multi-Human-Parsing_MHP/Nested_Adversarial_Networks/output_model.py", line 144
    tf.nn.softmax(tf.image.resize_images(net_bgfg.seg_layer,tf.shape(img_holder)[1:3]),1)[:,:,:,1],
     ^
SyntaxError: invalid syntax
`
What must be the value class_num to be passed from out_sample?

**Comment by ZhaoJ9014** [comment]
Hi,

Thank you for your question.

We have updated the code. Please have a check and feel free to contact us if you have further questions.

Thank you and best regards.
