### ISSUE TITLE
the pictures mentioned in train.list (in NAN folder)  are not exist

### ISSUE THREAD

**Issue by pei0113** [ZhaoJ9014/Multi-Human-Parsing_MHP#7]
the pictures mentioned in train.list (in NAN folder)  are not exist,could you provide them?
![problem](https://user-images.githubusercontent.com/42086087/45215513-39f37b80-b2d0-11e8-8859-2f79fc00a4c2.JPG)

**Comment by ZhaoJ9014** [comment]
Hi, You can download these images from VOC2012, which are publicly available. Thank you very much.

**Comment by archenroot** [comment]
@pei0113 - [VOC2012 Dataset](wget http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar)
