### ISSUE TITLE
Add pretrained models

### ISSUE THREAD

**Issue by impredicative** [ZhaoJ9014/Multi-Human-Parsing_MHP#9]
Please add pretrained models for use and maybe also for transfer learning. Thanks.

**Comment by ZhaoJ9014** [comment]
The pre-trained models will be released in near future. Thx.

**Comment by andrewjong** [comment]
@ZhaoJ9014 Any hint as to when pretrained models will be released? Weeks? Months?
Really cool work! Thank you for your effort.

**Comment by impredicative** [comment]
@ZhaoJ9014 Where is it?
